// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CodeDBQueryService.proto

#ifndef PROTOBUF_CodeDBQueryService_2eproto__INCLUDED
#define PROTOBUF_CodeDBQueryService_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_CodeDBQueryService_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsCodeDBQueryRequestImpl();
void InitDefaultsCodeDBQueryRequest();
void InitDefaultsCodeDBQueryResponseImpl();
void InitDefaultsCodeDBQueryResponse();
inline void InitDefaults() {
  InitDefaultsCodeDBQueryRequest();
  InitDefaultsCodeDBQueryResponse();
}
}  // namespace protobuf_CodeDBQueryService_2eproto
namespace CodeSmithy {
class CodeDBQueryRequest;
class CodeDBQueryRequestDefaultTypeInternal;
extern CodeDBQueryRequestDefaultTypeInternal _CodeDBQueryRequest_default_instance_;
class CodeDBQueryResponse;
class CodeDBQueryResponseDefaultTypeInternal;
extern CodeDBQueryResponseDefaultTypeInternal _CodeDBQueryResponse_default_instance_;
}  // namespace CodeSmithy
namespace CodeSmithy {

// ===================================================================

class CodeDBQueryRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CodeSmithy.CodeDBQueryRequest) */ {
 public:
  CodeDBQueryRequest();
  virtual ~CodeDBQueryRequest();

  CodeDBQueryRequest(const CodeDBQueryRequest& from);

  inline CodeDBQueryRequest& operator=(const CodeDBQueryRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CodeDBQueryRequest(CodeDBQueryRequest&& from) noexcept
    : CodeDBQueryRequest() {
    *this = ::std::move(from);
  }

  inline CodeDBQueryRequest& operator=(CodeDBQueryRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CodeDBQueryRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CodeDBQueryRequest* internal_default_instance() {
    return reinterpret_cast<const CodeDBQueryRequest*>(
               &_CodeDBQueryRequest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(CodeDBQueryRequest* other);
  friend void swap(CodeDBQueryRequest& a, CodeDBQueryRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CodeDBQueryRequest* New() const PROTOBUF_FINAL { return New(NULL); }

  CodeDBQueryRequest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CodeDBQueryRequest& from);
  void MergeFrom(const CodeDBQueryRequest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CodeDBQueryRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CodeSmithy.CodeDBQueryRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_CodeDBQueryService_2eproto::TableStruct;
  friend void ::protobuf_CodeDBQueryService_2eproto::InitDefaultsCodeDBQueryRequestImpl();
};
// -------------------------------------------------------------------

class CodeDBQueryResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:CodeSmithy.CodeDBQueryResponse) */ {
 public:
  CodeDBQueryResponse();
  virtual ~CodeDBQueryResponse();

  CodeDBQueryResponse(const CodeDBQueryResponse& from);

  inline CodeDBQueryResponse& operator=(const CodeDBQueryResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CodeDBQueryResponse(CodeDBQueryResponse&& from) noexcept
    : CodeDBQueryResponse() {
    *this = ::std::move(from);
  }

  inline CodeDBQueryResponse& operator=(CodeDBQueryResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CodeDBQueryResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CodeDBQueryResponse* internal_default_instance() {
    return reinterpret_cast<const CodeDBQueryResponse*>(
               &_CodeDBQueryResponse_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(CodeDBQueryResponse* other);
  friend void swap(CodeDBQueryResponse& a, CodeDBQueryResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CodeDBQueryResponse* New() const PROTOBUF_FINAL { return New(NULL); }

  CodeDBQueryResponse* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CodeDBQueryResponse& from);
  void MergeFrom(const CodeDBQueryResponse& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CodeDBQueryResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:CodeSmithy.CodeDBQueryResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_CodeDBQueryService_2eproto::TableStruct;
  friend void ::protobuf_CodeDBQueryService_2eproto::InitDefaultsCodeDBQueryResponseImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CodeDBQueryRequest

// -------------------------------------------------------------------

// CodeDBQueryResponse

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace CodeSmithy

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_CodeDBQueryService_2eproto__INCLUDED
